Parameters:
  LambdaFunctionArn:
    Type: String
    Description: ARN of the RSS Feed Processor Lambda function

Resources:
  EventBridgeSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: rss-feed-processor-schedule
      Description: Runs the RSS Feed Processor Lambda function every hour
      ScheduleExpression: rate(10 minutes)
      FlexibleTimeWindow: 
        Mode: FLEXIBLE
        MaximumWindowInMinutes: 1
      Target:
        Arn: !Ref LambdaFunctionArn