AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Role for RSS Feed Processor Lambda Function with Environment Variable Encryption'

Parameters:
  LambdaExecutionRoleName:
    Type: String
    Description: "Name of the Lambda Execution Role"
  LambdaKMSKeyArn:
    Type: String
    Description: "ARN of the KMS Key for Lambda environment variable encryption"
  Region:
    Type: String
    Description: "AWS Region for deployment"
    Default: "us-east-1"

Resources:
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref LambdaExecutionRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Policies:
        - PolicyName: 'RSSFeedProcessorLambdaPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:*'
                  - 'dynamodb:*'
                  - 's3:*'
                  - 'lambda:*'
                  - 'logs:*'
                  - 'xray:*'
                  - 'cloudwatch:*'
                  - 'events:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'kms:Decrypt'
                  - 'kms:GenerateDataKey'
                Resource: !Ref LambdaKMSKeyArn

Outputs:
  LambdaRoleArn:
    Description: 'ARN of the Lambda Execution Role'
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
       Name: !Sub '${AWS::StackName}-LambdaRoleArn'
  LambdaKMSKeyArn:
    Description: 'ARN of the KMS Key for Lambda'
    Value: !Ref LambdaKMSKeyArn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaKMSKeyArn'
  Region:
    Description: 'AWS Region for deployment'
    Value: !Ref Region
    Export:
      Name: !Sub '${AWS::StackName}-Region'