AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for RSS Feed Processor SQS Queue'

Parameters:
  SQSQueueName:
    Type: String
    Description: ""

Resources:
  RSSFeedQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref SQSQueueName
      VisibilityTimeout: 900 # Should be set to the 3rd standard deviation of your lambda runtime distribution.
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt RSSFeedDLQ.Arn
        maxReceiveCount: 3

  RSSFeedDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AWS::StackName}-rss-feed-dlq'

Outputs:
  QueueURL:
    Description: 'URL of the SQS queue for RSS feeds'
    Value: !Ref RSSFeedQueue
    Export:
      Name: !Sub '${AWS::StackName}-RSSFeedQueueURL'

  DLQueueURL:
    Description: 'URL of the Dead Letter Queue for RSS feeds'
    Value: !Ref RSSFeedDLQ
    Export:
      Name: !Sub '${AWS::StackName}-RSSFeedDLQueueURL'